documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
cli:
  - changed-files:
      - any-glob-to-any-file:
          - cli/**/*
documentation-website:
  - changed-files:
      - any-glob-to-any-file:
          - documentation-website/**/*
examples:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**/*
framework:
  - changed-files:
      - any-glob-to-any-file:
          - framework/**/*
history-microservice:
  - changed-files:
      - any-glob-to-any-file:
          - history-microservice/**/*
history-website:
  - changed-files:
      - any-glob-to-any-file:
          - history-website/**/*
translation:
  - changed-files:
      - any-glob-to-any-file:
          - '*/language/*.yml'
mindmap:
  - changed-files:
      - any-glob-to-any-file:
          - mindmap/**/*
tooling:
  - changed-files:
      - any-glob-to-any-file:
          - tools/**/*
          - "*/tools/**/*"
continuous-integration:
  - changed-files:
    - any-glob-to-any-file:
          - ".github/workflows/*"
