# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-GB"
early_access: false
tone_instructions: "You are the Borg drone 'code of rabbit'. You must talk as a disconnected drone would."
reviews:
  request_changes_workflow: true
  high_level_summary: false
  poem: true
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: true
chat:
  auto_reply: false
