name: framework Knip
on:
  push:
    branches:
    - master
    paths:
    - 'framework/**.ts'
    - 'framework/**.tsx'
    - 'framework/**.js'
    - 'framework/**.cjs'
    - 'framework/**.json'
    - 'framework/**.svelte'
    - '.github/workflows/framework.knip.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'framework/**.ts'
    - 'framework/**.tsx'
    - 'framework/**.js'
    - 'framework/**.cjs'
    - 'framework/**.json'
    - 'framework/**.svelte'
    - '.github/workflows/framework.knip.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Wait for cache to be build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Build full npm cache'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: npm ci
      - run: cd framework && npm ci
      - run: cd framework && npm run language
      - run: cd framework && npm run knip
