name: pull request size
on:
  pull_request:
    branches:
      - master
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Wait for cache to be build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Build full npm cache'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: npm install -g "https://github.com/Idrinth/check-pr-length.git#patch-1"
      - run: git remote add base https://github.com/idrinth/api-bench.git
      - run: git config --global user.email "prs@example.com"
      - run: git config --global user.name "PRS"
      - run: git fetch base master
      - run: git switch master
      - run: git remote add pullrequest "https://github.com/${{github.event.pull_request.head.repo.full_name}}"
      - run: git fetch pullrequest "${GITHUB_HEAD_REF}"
      - run: git switch $GITHUB_HEAD_REF
      - run: check-pr-length --max=350 --total=500 --base=master --silent=false --exclude="package-lock.json;*/package-lock.json"
