name: Hadolint
on:
  push:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/hadolint.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'containers/*/Dockerfile'
      - '.github/workflows/hadolint.yml'
jobs:
  lint-gitlab:
    name: Gitlab
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /usr/local/bin/hadolint
      - run: hadolint containers/api-bench-gitlab-runner/Dockerfile
  lint-gitea:
    name: Gitea
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /usr/local/bin/hadolint
      - run: hadolint containers/api-bench-gitea-action/Dockerfile
  lint-framework:
    name: Framework
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /usr/local/bin/hadolint
      - run: hadolint containers/api-bench/Dockerfile
  lint-microservice:
    name: History Microservice
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /usr/local/bin/hadolint
      - run: hadolint containers/api-bench-history-microservice/Dockerfile
  lint-website:
    name: History Website
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /usr/local/bin/hadolint
      - run: hadolint containers/api-bench-history-website/Dockerfile
  lint-build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install shellcheck -y
      - run: wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
      - run: sudo mv hadolint-Linux-x86_64 /usr/local/bin/hadolint
      - run: sudo chmod +x /usr/local/bin/hadolint
      - run: hadolint containers/api-bench-build/Dockerfile
