name: mindmap spellcheck
on:
  push:
    branches:
    - master
    paths:
    - 'mindmap/data.yml'
    - '.github/workflows/mindmap.spellcheck.yml'
    - '.dictionary.txt'
  pull_request:
    branches:
    - master
    paths:
    - 'mindmap/data.yml'
    - '.github/workflows/mindmap.spellcheck.yml'
    - '.dictionary.txt'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: cd mindmap && npm ci
      - run: cd mindmap && npm run spellcheck
